//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.17.0.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming



export interface Classroom {
    id: number;
    number?: string | undefined;
    students?: Student[] | undefined;
    teacher?: Teacher | undefined;
}

export interface Student {
    id: number;
    name?: string | undefined;
    classroom: Classroom;
    courses?: Course[] | undefined;
}

export interface Course {
    id: number;
    title?: string | undefined;
    students?: Student[] | undefined;
    author?: Teacher | undefined;
    editor?: Teacher | undefined;
}

export interface Teacher {
    id: number;
    name?: string | undefined;
    classroomId?: number | undefined;
    classroom?: Classroom | undefined;
    coursesWritten?: Course[] | undefined;
    coursesEdited?: Course[] | undefined;
}

export interface FileResponse {
    data: Blob;
    status: number;
    fileName?: string;
    headers?: { [name: string]: any };
}